# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cf9a787c070478465d032752bd774964c35145ca6b72c30d309265060787ab88adc10dcf53f342c38ee60f7184ab607c8ac306ab015f39a58bed3fc30d714ab

test:
  secret_key_base: cbd43014d5e87fb7f82e971fe01ccb46ff8a3f1a71b0e96ab0dd47a1b52f6a06c121ac8319be1a6c51423684e6489cc5f591ba7590ff244c5ab9dd7ead4a3b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
